apiVersion: v1
data:
  DATABASE: postgres
  DEBUG: "0"
#  DJANGO_ALLOWED_HOSTS: nginx 10.0.0.0/8 localhost 127.0.0.1 [::1] 
  DJANGO_ALLOWED_HOSTS: '*'
  SECRET_KEY: xiJX1tuCzX19uAeYMTyMmYZmlLcMR02
  SQL_DATABASE: hello_django_prod
  SQL_ENGINE: django.db.backends.postgresql
  SQL_HOST: db
  SQL_PORT: "5432"
kind: ConfigMap
metadata:
  labels:
    service: web-env
  name: env